<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Medical Prescription - #{{ str_pad($appointment->id, 5, '0', STR_PAD_LEFT) }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 14px; color: #333; line-height: 1.5; margin: 0; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #0F172A; padding-bottom: 20px; margin-bottom: 30px; }
        .clinic-name { font-size: 28px; font-weight: bold; color: #0F172A; margin: 0; }
        .clinic-details { font-size: 12px; color: #666; margin-top: 5px; }
        .row { width: 100%; margin-bottom: 20px; clear: both; }
        .col-half { width: 48%; float: left; }
        .col-half:last-child { float: right; }
        .label { font-weight: bold; color: #555; font-size: 12px; text-transform: uppercase; margin-bottom: 3px; }
        .value { font-size: 15px; margin-bottom: 15px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        .section-title { font-size: 16px; font-weight: bold; color: #0F172A; text-transform: uppercase; border-bottom: 1px solid #0F172A; padding-bottom: 5px; margin-top: 40px; margin-bottom: 15px; }
        .content-box { background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; min-height: 100px; border-radius: 5px; white-space: pre-wrap; }
        .footer { position: fixed; bottom: 30px; left: 0px; right: 0px; text-align: center; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
        .signature-line { margin-top: 80px; width: 250px; float: right; text-align: center; border-top: 1px solid #333; padding-top: 5px; }
        .clearfix::after { content: ""; clear: both; display: table; }
    </style>
</head>
<body>

    <div class="header">
        <h1 class="clinic-name">ClearOptics Eye Care</h1>
        <div class="clinic-details">
            123 Visionary Way, Clear City, 4000<br>
            Phone: (049) 123-4567 | Email: support@clearoptics.com
        </div>
    </div>

    <div class="row clearfix">
        <div class="col-half">
            <div class="label">Patient Name</div>
            <div class="value">{{ $appointment->patient_name }}</div>
            
            <div class="label">Contact</div>
            <div class="value">{{ $appointment->patient_phone ?? $appointment->patient_email ?? 'N/A' }}</div>
        </div>
        <div class="col-half">
            <div class="label">Date of Consultation</div>
            <div class="value">{{ $appointment->appointment_date->format('F d, Y') }}</div>
            
            <div class="label">Service Provided</div>
            <div class="value">{{ $appointment->service }}</div>
        </div>
    </div>

    <div class="section-title">Clinical Diagnosis</div>
    <div class="content-box">{{ $appointment->diagnosis ?? 'No diagnosis recorded.' }}</div>

    <div class="section-title">Medical Prescription (Rx)</div>
    <div class="content-box">{{ $appointment->prescription ?? 'No prescription recorded.' }}</div>

    <div class="clearfix">
        <div class="signature-line">
            <strong>Attending Optometrist / Ophthalmologist</strong><br>
            License No: ___________
        </div>
    </div>

    <div class="footer">
        This document is officially generated by the EyeCarePortal System.<br>
        Date Printed: {{ now()->format('F d, Y h:i A') }}
    </div>

</body>
</html>